SC-2040: create schema for postgres db
dimagi/hq_superset pull request #1
Opened 2022-03-31 12:00 UTC by akashkj

Changes to create schema in the DB. This is a sub-task under automatic roles creation US.

TODO - Adding unit test for postgres specific code, I'm looking at some mock utility lib that can be used for postgres testing.

2022-04-01 09:51 UTC, sravfeyn commented on hq_superset/model/db_info.py
> +class DbInfo(object):
Can we not use the URL style connection string to avoid this class?

2022-04-04 16:21 UTC, proteusvacuum requested changes

2022-04-08 09:20 UTC, kaapstorm reviewed
It looks like we are trying to reinvent a very well-established wheel. Is there a reason we aren't using SQLAlchemy + Alembic [as Superset already does](https://github.com/apache/superset/blob/2631558ac4ba596b24876a9b0702bbf3a6bfbb38/superset/migrations/alembic.ini#L20) for managing our database?

2022-05-02 09:22 UTC, sravfeyn commented
Actually, this could be much simpler. I have created a util here to create a schema https://github.com/dimagi/hq_superset/pull/6/commits/c35339e28dbe2130da34fda24e248b8e9094bb16

2022-05-03 06:14 UTC, akashkj commented
That looks much simpler indeed @sravfeyn 
Will close this one

2022-05-03 06:14 UTC, closed without merging